### PR TITLE
add image-preview loading

### PR DESCRIPTION
**Pull request by keyone2693**
add loading image before each file preview

### CODE REVIEW

**Comment by KOSSOKO** [comment]
Thanks for adding this feature.
How to use it ? So i could update the plugin, test it and send feedback.

**Comment by peterfreeman** [comment]
@KOSSOKO Just check out the master branch of the repo and run `ng serve`. I will update the npm package within the next days.

**Comment by keyone2693** [comment]
waiting for npm release :)

**Comment by peterfreeman** [comment]
Done.

**Comment by KOSSOKO** [comment]
Thanks

**Comment by KOSSOKO** [comment]
Tested and very well done, thanks

**Comment by tatianabarboza3** [comment]
Hi, I don't understand how this feature works. Can you help me, please? Do I need to add an additional tag? I don't see it in the demos. @KOSSOKO @keyone2693 @peterfreeman

**Pull request merged**
